version: '3.8'

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      my_network:
        name: laravel
        external: true

  # Nginx service
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    tty: true
    ports:
      - "3001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      my_network:
        name: laravel
        external: true

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      my_network:
        name: laravel
        external: true

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
