name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DAD_SSH_PRIVATE_KEY }}

      - name: Add GitHub.com to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -T git@github.com

      - name: Add production server as a remote
        run: |
          git remote remove production || true
          git remote add production ssh://root@94.237.56.48/var/repo/dialadoc-backend

      - name: Enable SSH debugging
        run: |
          echo 'LogLevel DEBUG1' >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      # - name: Push to Production Server
      #   run: git push production main
